#!/usr/bin/env python3
import argparse
import io
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image, ImageFilter, ImageOps


ROOT = Path(__file__).resolve().parents[1]
BACKUP_DIR = ROOT / "backups" / "coupon-images"
TARGET_SIZE = (1200, 675)
BUCKET = "images"
STORAGE_PREFIX = "coupons/card"


def load_env(path: Path) -> dict:
    env = {}
    if not path.exists():
        return env
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def request_json(url: str, anon_key: str):
    req = urllib.request.Request(
        url,
        headers={
            "apikey": anon_key,
            "Authorization": f"Bearer {anon_key}",
            "Accept": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=40) as res:
        return json.loads(res.read().decode("utf-8"))


def request_bytes(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "wffrhasah-image-normalizer/1.0"})
    with urllib.request.urlopen(req, timeout=60) as res:
        return res.read()


def patch_coupon_image(supabase_url: str, anon_key: str, coupon_id: str, public_url: str):
    endpoint = f"{supabase_url}/rest/v1/coupons?id=eq.{urllib.parse.quote(coupon_id)}"
    payload = json.dumps({"image": public_url}).encode("utf-8")
    req = urllib.request.Request(
        endpoint,
        data=payload,
        method="PATCH",
        headers={
            "apikey": anon_key,
            "Authorization": f"Bearer {anon_key}",
            "Content-Type": "application/json",
            "Prefer": "return=minimal",
        },
    )
    with urllib.request.urlopen(req, timeout=40) as res:
        return res.status


def upload_storage(supabase_url: str, anon_key: str, path: str, image_bytes: bytes):
    endpoint = f"{supabase_url}/storage/v1/object/{BUCKET}/{path}"
    req = urllib.request.Request(
        endpoint,
        data=image_bytes,
        method="POST",
        headers={
            "apikey": anon_key,
            "Authorization": f"Bearer {anon_key}",
            "Content-Type": "image/jpeg",
            "x-upsert": "true",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as res:
        return res.status


def describe_error(exc: Exception) -> str:
    if isinstance(exc, urllib.error.HTTPError):
        try:
            body = exc.read().decode("utf-8", errors="replace")
        except Exception:
            body = ""
        return f"HTTP {exc.code}: {body or exc.reason}"
    return str(exc)


def public_storage_url(supabase_url: str, path: str) -> str:
    encoded_path = "/".join(urllib.parse.quote(part) for part in path.split("/"))
    return f"{supabase_url}/storage/v1/object/public/{BUCKET}/{encoded_path}"


def normalize_image(raw: bytes) -> bytes:
    source = Image.open(io.BytesIO(raw)).convert("RGB")
    source = ImageOps.exif_transpose(source)

    canvas_w, canvas_h = TARGET_SIZE
    base = Image.new("RGB", TARGET_SIZE, (248, 249, 255))

    # Soft blurred wash from the source image keeps every coupon visually related
    # to its original artwork without stretching readable text.
    wash = ImageOps.fit(source, TARGET_SIZE, method=Image.Resampling.LANCZOS)
    wash = wash.filter(ImageFilter.GaussianBlur(radius=28))
    wash = Image.blend(base, wash, 0.16)

    max_w = int(canvas_w * 0.88)
    max_h = int(canvas_h * 0.80)
    fitted = source.copy()
    fitted.thumbnail((max_w, max_h), Image.Resampling.LANCZOS)

    x = (canvas_w - fitted.width) // 2
    y = (canvas_h - fitted.height) // 2
    wash.paste(fitted, (x, y))

    out = io.BytesIO()
    wash.save(out, format="JPEG", quality=88, optimize=True, progressive=True)
    return out.getvalue()


def coupon_query(supabase_url: str, limit: int, only_missing_storage: bool) -> str:
    params = {
        "select": "id,image",
        "image": "not.is.null",
        "order": "created_at.desc",
        "limit": str(limit),
    }
    url = f"{supabase_url}/rest/v1/coupons?{urllib.parse.urlencode(params)}"
    if only_missing_storage:
        # Avoid repeatedly normalizing images already generated by this script.
        url += f"&image=not.like.*%2F{STORAGE_PREFIX}%2F*"
    return url


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Normalize coupon images to card-friendly 1200x675 files and update coupons.image."
    )
    parser.add_argument("--limit", type=int, default=10, help="Number of coupons to process.")
    parser.add_argument("--apply", action="store_true", help="Upload images and update coupons.image.")
    parser.add_argument(
        "--include-already-normalized",
        action="store_true",
        help="Also process images already pointing to coupons/card.",
    )
    args = parser.parse_args()

    env = {**load_env(ROOT / ".env"), **os.environ}
    supabase_url = env.get("SUPABASE_URL", "").rstrip("/")
    anon_key = env.get("SUPABASE_ANON_KEY", "")
    write_key = env.get("SUPABASE_SERVICE_ROLE_KEY", "") or anon_key

    if not supabase_url or not anon_key:
        print("Missing SUPABASE_URL or SUPABASE_ANON_KEY in .env/environment.", file=sys.stderr)
        return 2
    if args.apply and write_key == anon_key:
        print(
            "Warning: SUPABASE_SERVICE_ROLE_KEY is not set. "
            "Storage upload may fail if anon is blocked by RLS.",
            file=sys.stderr,
        )

    if args.limit <= 0:
        print("--limit must be greater than 0", file=sys.stderr)
        return 2

    dry_run = not args.apply
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    backup_path = BACKUP_DIR / f"coupon-image-backup-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.jsonl"

    rows = request_json(
        coupon_query(
            supabase_url,
            args.limit,
            only_missing_storage=not args.include_already_normalized,
        ),
        anon_key,
    )

    print(f"Found {len(rows)} coupons. mode={'DRY RUN' if dry_run else 'APPLY'}")
    print(f"Backup file: {backup_path.relative_to(ROOT)}")

    processed = 0
    with backup_path.open("w", encoding="utf-8") as backup:
        for row in rows:
            coupon_id = str(row.get("id") or "").strip()
            original_url = str(row.get("image") or "").strip()
            if not coupon_id or not original_url:
                continue

            backup.write(json.dumps({"id": coupon_id, "image": original_url}, ensure_ascii=False) + "\n")

            try:
                raw = request_bytes(original_url)
                normalized = normalize_image(raw)
                storage_path = f"{STORAGE_PREFIX}/{coupon_id}.jpg"
                new_url = public_storage_url(supabase_url, storage_path)

                if dry_run:
                    print(f"[dry-run] {coupon_id}: {len(raw)} bytes -> {len(normalized)} bytes")
                else:
                    upload_storage(supabase_url, write_key, storage_path, normalized)
                    patch_coupon_image(supabase_url, write_key, coupon_id, new_url)
                    print(f"[updated] {coupon_id}: {new_url}")

                processed += 1
                time.sleep(0.15)
            except (urllib.error.HTTPError, urllib.error.URLError, OSError, ValueError) as exc:
                print(f"[skip] {coupon_id}: {describe_error(exc)}", file=sys.stderr)

    print(f"Processed {processed}/{len(rows)} coupons.")
    if dry_run:
        print("No database/storage changes were made. Re-run with --apply to update coupons.image.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
